buckets:
  - extras

dependencies:
  - name: git
    description: Git
    required: true

devDependencies:
  #  Runtime Managers
  - name: nvm
    description: Node Version Manager
    required: true
    postInstall: nvm install lts; nvm use lts
  
  #  Security Tools
  - name: mkcert
    description: Local development certificates
    required: false
  
  #  Package Managers
  - name: yarn
    description: Node.js dependency manager
    required: true
  - name: pnpm
    description: Fast, disk space efficient package manager for Node.js
    required: true

  #  Code Editors
  - name: vscode
    description: Visual Studio Code editor
    required: false
  - name: zed
    description: Zed code editor
    required: false
  - name: cursor
    description: Cursor AI-powered code editor
    required: false

  # Communication Tools
  - name: slack
    description: Slack messaging app
    required: false
  - name: zoom
    description: Zoom video conferencing app
    required: false
  - name: microsoft-teams
    description: Microsoft Teams messaging app
    required: false
  
system:
  sshAgent:
    enabled: true
    autoStart: true
  git:
    configureSSH: true
    description: Configure Git with SSH integration and custom settings
    config:
      global:
        init:
          defaultBranch: main
        user:
          name: Your Name # Replace with your name
          email: your_email@example.com # Replace with your email
        core:
          sshCommand: C:/Windows/System32/OpenSSH/ssh.exe
        push:
          autoSetupRemote: true
