apps:
  #  Terminals
  - name: iterm2
    required: true

  #  Code Editors
  - name: visual-studio-code
    required: true

  #  Runtime Managers
  - name: nvm
    required: false

  #  Package Managers
  - name: yarn
    required: true
  - name: pnpm
    required: true

git:
  user:
    name: "Your Name"
    email: "your_name@example.com"
